name: SPFxDemo-CICD

on:
  push:
    branches: [ main ]
    
env:
  APP_FILE_PATH: '**/*.sppkg'
  SEND_MAIL: 'false'
  DEVSITEURL: ${{ secrets.DEVSITEURL }}
  TENANT: ${{ secrets.TENANT }}
  APPID: ${{ secrets.APPID }}
  BASEENCODEDSTRING: ${{ secrets.BASEENCODEDSTRING }}
  CERTPWD: ${{ secrets.CERTPWD }}
  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v1
      
    # Setup node.js runtime
    - name: Use Node.js 14.18.1
      uses: actions/setup-node@v1
      with:
        node-version: 14.18.1
    # npm install
    - name: Run npm install
      run: |
        npm install
    
    # gulp bundle and package solution
    - name: Bundle 
      run: |
        gulp bundle --ship --warnoff
    - name: Package Solution
      run: |
        gulp package-solution --ship 
    - name: Set pkgname
      id: get-pkgname
      run: |
        echo ::set-output name=pkgname::$(find . -name *.sppkg)
    - name: Use the output
      run: |
        echo 'The output pkgname is ${{ steps.get-pkgname.outputs.pkgname }}'  
    - name: PowerShell script
      uses: Amadevus/pwsh-script@v2.0.1
      with:
        # PowerShell script to execute in Actions-hydrated context
        script: |
          Install-Module PnP.PowerShell -AllowPrerelease -Scope "CurrentUser" -Verbose -AllowClobber -Force
          Connect-PnPOnline -Url $DEVSITEURL -ClientId $APPID -CertificateBase64Encoded $BASEENCODEDSTRING -CertificatePassword (ConvertTo-SecureString -AsPlainText $CERTPWD -Force) -Tenant $TENANT
          
        
