name: SPFxDemo-CICD

on:
  push:
    branches: [ main ]
    
env:
  APP_FILE_PATH: '**/*.sppkg'
  SEND_MAIL: 'false'
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: RunPowershellScriptFromRepo
      env: #Set secrets as environment variables
        DEVSITEURL: ${{ secrets.DEVSITEURL }}
        TENANT: ${{ secrets.TENANT }}
        APPID: ${{ secrets.APPID }}
        BASEENCODEDSTRING: ${{ secrets.BASEENCODEDSTRING }}
        CERTPWD: ${{ secrets.CERTPWD }}
        packagePath: ${{ steps.get-pkgname.outputs.pkgname }}
      run: |
        Write-Host "Installing PnP Module"
        Install-Module -Name PnP.PowerShell -Force -Scope "CurrentUser"
        Connect-PnPOnline -Url ${{ secrets.DEVSITEURL }} -ClientId ${{ secrets.APPID }} -CertificateBase64Encoded ${{ secrets.BASEENCODEDSTRING }} -CertificatePassword (ConvertTo-SecureString -AsPlainText ${{ secrets.CERTPWD }} -Force) -Tenant ${{ secrets.TENANT }}
      shell: pwsh
          
        
