# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
    
env:
  APP_FILE_PATH: '**/*.sppkg'
  SEND_MAIL: 'false'
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
  
    steps:
      # Checkout code
      - name: Testing
        env: #Set secrets as environment variables
          DEVSITEURL: ${{ secrets.DEVSITEURL }}
        run: |
          Write-Host "Installing PnP Module" 
          Write-OutPut "Test env secret - " ${{ Dev.secrets.TESTSECRET }}
          Install-Module -Name PnP.PowerShell -Force -Scope "CurrentUser"
          Write-Host "Connecting to SharePoint Site"
          Connect-PnPOnline -Url ${{ secrets.DEVSITEURL }} -ClientId ${{ secrets.APPID }} -CertificateBase64Encoded ${{ secrets.BASEENCODEDSTRING }} -CertificatePassword (ConvertTo-SecureString -AsPlainText ${{ secrets.CERTPWD }} -Force) -Tenant ${{ secrets.TENANT }}
          Write-Host "Step Done"
        shell: pwsh
